// Generated by CoffeeScript 1.6.2
(function() {
  var EntityGraphic;

  exports.EntityGraphic = EntityGraphic = (function() {
    function EntityGraphic() {}

    EntityGraphic.prototype.setEntity = function(entity_) {
      this.entity_ = entity_;
    };

    EntityGraphic.prototype.draw = function(context) {};

    EntityGraphic.prototype.update = function() {};

    EntityGraphic.prototype.getPos = function() {
      return {
        x: this.entity_.getPos().x - this.getWidth() / 2 + this.getOffset().x,
        y: this.entity_.getPos().y - this.getHeight() / 2 + this.getOffset().y
      };
    };

    EntityGraphic.prototype.getCenter = function() {
      return {
        x: this.entity_.getPos().x + this.getOffset().x,
        y: this.entity_.getPos().y + this.getOffset().y
      };
    };

    EntityGraphic.prototype.getOffset = function() {
      var _ref;

      return (_ref = this.offset_) != null ? _ref : {
        x: 0,
        y: 0
      };
    };

    EntityGraphic.prototype.setOffset = function(offset_) {
      this.offset_ = offset_;
    };

    EntityGraphic.prototype.setWidth = function(width_) {
      this.width_ = width_;
    };

    EntityGraphic.prototype.getWidth = function() {
      var _ref;

      return (_ref = this.width_) != null ? _ref : this.entity_.getRadius() * 2;
    };

    EntityGraphic.prototype.setHeight = function(height_) {
      this.height_ = height_;
    };

    EntityGraphic.prototype.getHeight = function() {
      var _ref;

      return (_ref = this.height_) != null ? _ref : this.entity_.getRadius() * 2;
    };

    return EntityGraphic;

  })();

}).call(this);

/*
//@ sourceMappingURL=entity_graphic.map
*/
