// Generated by CoffeeScript 1.6.2
(function() {
  var Factory;

  exports.Factory = Factory = (function() {
    function Factory() {}

    Factory.create = function(factoryClass, type) {
      var _ref;

      if ((_ref = factoryClass.instance) == null) {
        factoryClass.instance = new factoryClass;
      }
      return factoryClass.instance.create(type);
    };

    Factory.prototype.create = function(type_) {
      var result;

      this.type_ = type_;
      if (this.type_ in this.creationMethods_) {
        result = this.creationMethods_[this.type_].apply(this);
        return this.processResult_(result);
      } else {
        throw "type '" + this.type_ + "' was not found";
      }
    };

    Factory.prototype.processResult_ = function(result) {
      return result;
    };

    return Factory;

  })();

}).call(this);

/*
//@ sourceMappingURL=factory.map
*/
