// Generated by CoffeeScript 1.6.2
(function() {
  var Graphic;

  exports.Graphic = Graphic = (function() {
    function Graphic(sprite_) {
      this.sprite_ = sprite_;
      this.pos_ = {
        x: 0,
        y: 0
      };
      this.animating_ = false;
    }

    Graphic.prototype.setPos = function(pos_) {
      this.pos_ = pos_;
    };

    Graphic.prototype.draw = function(ctx) {
      var x, y;

      if (!this.isLoaded_()) {
        return;
      }
      x = this.pos_.x - this.sprite_.frameW / 2;
      y = this.pos_.y - this.sprite_.frameH / 2;
      return this.sprite_.draw(ctx, x, y);
    };

    Graphic.prototype.getFrame = function() {
      return this.sprite_.getFrame().col;
    };

    Graphic.prototype.runOnce = function() {
      if (!this.isLoaded_()) {
        return;
      }
      this.animating_ = true;
      return this.sprite_.runLoop(function() {
        return this.loopDone_ = true;
      });
    };

    Graphic.prototype.isAnimating = function() {
      return this.animating_;
    };

    Graphic.prototype.isLoaded_ = function() {
      return this.sprite_.frameW != null;
    };

    return Graphic;

  })();

}).call(this);

/*
//@ sourceMappingURL=graphic.map
*/
