// Generated by CoffeeScript 1.6.2
(function() {
  var game,
    _this = this;

  game = new Game;

  window.onblur = function() {
    return game.stop();
  };

  window.onfocus = function() {
    return game.run();
  };

  $(window).on('resize', function() {
    return game.resize();
  });

  game.run();

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
