// Generated by CoffeeScript 1.6.2
(function() {
  exports.Position = {
    equals: function(pos1, pos2) {
      return pos1.x === pos2.x && pos1.y === pos2.y;
    },
    add: function(pos1, pos2) {
      return {
        x: pos1.x + pos2.x,
        y: pos1.y + pos2.y
      };
    },
    subtract: function(pos1, pos2) {
      return {
        x: pos1.x - pos2.x,
        y: pos1.y - pos2.y
      };
    },
    negate: function(pos) {
      return {
        x: -pos.x,
        y: -pos.y
      };
    },
    clone: function(pos) {
      return {
        x: pos.x,
        y: pos.y
      };
    }
  };

}).call(this);

/*
//@ sourceMappingURL=position.map
*/
